services:
  app:
    build: .
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command: ["MacBook Pro 16", "Dell XPS 15", "ThinkPad X1 Carbon"]
